import os
from dotenv import load_dotenv

load_dotenv()

KALSHI_ENV = os.getenv("KALSHI_ENV", "demo").lower()

# Optional overrides if Kalshi changes hosts (must include /trade-api/v2 for REST)
_DEFAULT_PROD_API = "https://api.elections.kalshi.com/trade-api/v2"
_DEFAULT_DEMO_API = "https://demo-api.kalshi.co/trade-api/v2"
if KALSHI_ENV == "prod":
    API_BASE_URL = os.getenv("KALSHI_API_BASE_URL", _DEFAULT_PROD_API)
else:
    API_BASE_URL = os.getenv("KALSHI_API_BASE_URL", _DEFAULT_DEMO_API)

_DEFAULT_PROD_WS = "wss://api.elections.kalshi.com/trade-api/ws/v2"
_DEFAULT_DEMO_WS = "wss://demo-api.kalshi.co/trade-api/ws/v2"
if KALSHI_ENV == "prod":
    WS_BASE_URL = os.getenv("KALSHI_WS_BASE_URL", _DEFAULT_PROD_WS)
else:
    WS_BASE_URL = os.getenv("KALSHI_WS_BASE_URL", _DEFAULT_DEMO_WS)

# Flask app defaults
WEB_HOST = "127.0.0.1"
WEB_PORT = 5000

# Dashboard/view defaults
ORDERBOOK_VIEW_DEPTH = 10
WS_LOG_MAXLEN = 5000
WS_LOG_DEFAULT_LIMIT = 200

# Data/compute cadence defaults
BRTI_RECALC_INTERVAL_SEC = 1.0
SNAPSHOT_RECALIBRATION_SEC = 30.0

# Reconciliation policy defaults
RECONCILIATION_TOP_N = 10
RECONCILIATION_PRICE_TOL_CENTS = 0.01
RECONCILIATION_QTY_TOL = 1.0
RECONCILIATION_CONSECUTIVE_BREACHES = 3

# Market selection defaults
MARKET_ASSET_DEFAULT = os.getenv("KALSHI_MARKET_ASSET", "BTC").upper()
MARKET_SELECTION_STATE_PATH = os.getenv(
    "KALSHI_MARKET_SELECTION_STATE_PATH",
    ".runtime/market_selection.json",
)


def _env_bool(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return bool(default)
    value = raw.strip().lower()
    return value in {"1", "true", "yes", "y", "on"}


def _env_int(name: str, default: int) -> int:
    raw = os.getenv(name)
    if raw is None:
        return int(default)
    try:
        return int(raw)
    except ValueError:
        return int(default)


def _env_float(name: str, default: float) -> float:
    raw = os.getenv(name)
    if raw is None:
        return float(default)
    try:
        return float(raw)
    except ValueError:
        return float(default)


# Execution runtime defaults
_EXECUTION_MODE_RAW = os.getenv("KALSHI_EXECUTION_MODE", "observe").strip().lower()
if _EXECUTION_MODE_RAW not in {"observe", "paper", "live"}:
    _EXECUTION_MODE_RAW = "observe"

EXECUTION_MODE = _EXECUTION_MODE_RAW
EXECUTION_ENABLED = _env_bool("KALSHI_EXECUTION_ENABLED", True)
EXECUTION_ALLOW_LIVE_IN_DEMO_ENV = _env_bool("KALSHI_EXECUTION_ALLOW_LIVE_IN_DEMO_ENV", False)
EXECUTION_LOOP_INTERVAL_SEC = max(0.05, _env_float("KALSHI_EXECUTION_LOOP_INTERVAL_SEC", 0.25))
EXECUTION_CONTRACT_SECONDS = max(60, _env_int("KALSHI_EXECUTION_CONTRACT_SECONDS", 900))

EXECUTION_MIN_PROBABILITY = min(1.0, max(0.0, _env_float("KALSHI_EXECUTION_MIN_PROBABILITY", 0.03)))
EXECUTION_MAX_PROBABILITY = min(1.0, max(EXECUTION_MIN_PROBABILITY, _env_float("KALSHI_EXECUTION_MAX_PROBABILITY", 0.97)))
EXECUTION_MIN_CONFIDENCE = min(0.5, max(0.0, _env_float("KALSHI_EXECUTION_MIN_CONFIDENCE", 0.01)))
EXECUTION_MIN_EDGE_CENTS = max(0.0, _env_float("KALSHI_EXECUTION_MIN_EDGE_CENTS", 0.5))
EXECUTION_TARGET_EDGE_CENTS = max(EXECUTION_MIN_EDGE_CENTS, _env_float("KALSHI_EXECUTION_TARGET_EDGE_CENTS", 2.0))
EXECUTION_MIN_TIMING_SCORE = min(1.0, max(0.0, _env_float("KALSHI_EXECUTION_MIN_TIMING_SCORE", 0.0)))
EXECUTION_REQUIRE_P_BOOK_CONFIRMATION = _env_bool("KALSHI_EXECUTION_REQUIRE_P_BOOK_CONFIRMATION", False)
EXECUTION_P_BOOK_MIN_QUALITY = min(1.0, max(0.0, _env_float("KALSHI_EXECUTION_P_BOOK_MIN_QUALITY", 0.1)))
EXECUTION_P_BOOK_MAX_DIVERGENCE = min(0.49, max(0.01, _env_float("KALSHI_EXECUTION_P_BOOK_MAX_DIVERGENCE", 0.35)))

EXECUTION_MAX_ORDER_CONTRACTS = max(1, _env_int("KALSHI_EXECUTION_MAX_ORDER_CONTRACTS", 150))
EXECUTION_MAX_OPEN_ORDERS = max(1, _env_int("KALSHI_EXECUTION_MAX_OPEN_ORDERS", 20))
EXECUTION_MAX_MARKET_CONTRACTS = max(1, _env_int("KALSHI_EXECUTION_MAX_MARKET_CONTRACTS", 600))
EXECUTION_MAX_DAILY_LOSS_CENTS = max(1, _env_int("KALSHI_EXECUTION_MAX_DAILY_LOSS_CENTS", 25_000))
EXECUTION_MIN_CASH_BUFFER_CENTS = max(0, _env_int("KALSHI_EXECUTION_MIN_CASH_BUFFER_CENTS", 2_000))

EXECUTION_ORDER_STALE_SEC = max(0.0, _env_float("KALSHI_EXECUTION_ORDER_STALE_SEC", 1.2))
EXECUTION_POST_ONLY = _env_bool("KALSHI_EXECUTION_POST_ONLY", False)
EXECUTION_ORDER_TIME_IN_FORCE = os.getenv("KALSHI_EXECUTION_ORDER_TIME_IN_FORCE", "gtc").strip().lower() or "gtc"

EXECUTION_EVENTS_MAXLEN = max(200, _env_int("KALSHI_EXECUTION_EVENTS_MAXLEN", 8_000))
EXECUTION_EVENTS_PATH = os.getenv("KALSHI_EXECUTION_EVENTS_PATH", ".runtime/execution_events.jsonl")
EXECUTION_PERFORMANCE_PATH = os.getenv("KALSHI_EXECUTION_PERFORMANCE_PATH", ".runtime/execution_performance.jsonl")


# Legacy/high-activity paper profile compatibility defaults
PAPER_ACTIVITY_PROFILE_ENABLED = _env_bool("KALSHI_PAPER_ACTIVITY_PROFILE_ENABLED", True)
PAPER_ACTIVITY_PROFILE = os.getenv("KALSHI_PAPER_ACTIVITY_PROFILE", "high_activity").strip().lower() or "high_activity"
PAPER_ACTIVITY_ALLOW_TAKER = _env_bool("KALSHI_PAPER_ACTIVITY_ALLOW_TAKER", True)
PAPER_ACTIVITY_AGGRESSIVE_EDGE_CENTS = max(0.0, _env_float("KALSHI_PAPER_ACTIVITY_AGGRESSIVE_EDGE_CENTS", 0.5))
PAPER_ACTIVITY_ORDER_STALE_SEC = max(0.0, _env_float("KALSHI_PAPER_ACTIVITY_ORDER_STALE_SEC", 0.8))
PAPER_ACTIVITY_FORCE_FILL_PER_WINDOW = _env_bool("KALSHI_PAPER_ACTIVITY_FORCE_FILL_PER_WINDOW", False)
PAPER_ACTIVITY_FALLBACK_TRIGGER_SEC = max(0.0, _env_float("KALSHI_PAPER_ACTIVITY_FALLBACK_TRIGGER_SEC", 30.0))
PAPER_ACTIVITY_FALLBACK_RETRY_SEC = max(0.2, _env_float("KALSHI_PAPER_ACTIVITY_FALLBACK_RETRY_SEC", 1.5))
PAPER_ACTIVITY_FALLBACK_MIN_EDGE_CENTS = max(0.0, _env_float("KALSHI_PAPER_ACTIVITY_FALLBACK_MIN_EDGE_CENTS", 0.1))
PAPER_ACTIVITY_FALLBACK_BYPASS_P_BOOK = _env_bool("KALSHI_PAPER_ACTIVITY_FALLBACK_BYPASS_P_BOOK", True)

PAPER_ACTIVITY_MIN_CONFIDENCE = min(0.5, max(0.0, _env_float("KALSHI_PAPER_ACTIVITY_MIN_CONFIDENCE", 0.0)))
PAPER_ACTIVITY_MIN_EDGE_CENTS = max(0.0, _env_float("KALSHI_PAPER_ACTIVITY_MIN_EDGE_CENTS", 0.5))
PAPER_ACTIVITY_MIN_TIMING_SCORE = min(1.0, max(0.0, _env_float("KALSHI_PAPER_ACTIVITY_MIN_TIMING_SCORE", 0.0)))
PAPER_ACTIVITY_REQUIRE_P_BOOK_CONFIRMATION = _env_bool("KALSHI_PAPER_ACTIVITY_REQUIRE_P_BOOK_CONFIRMATION", False)
PAPER_ACTIVITY_P_BOOK_MIN_QUALITY = min(1.0, max(0.0, _env_float("KALSHI_PAPER_ACTIVITY_P_BOOK_MIN_QUALITY", 0.0)))
PAPER_ACTIVITY_P_BOOK_MAX_DIVERGENCE = min(0.49, max(0.01, _env_float("KALSHI_PAPER_ACTIVITY_P_BOOK_MAX_DIVERGENCE", 0.49)))


# Paper fill-model compatibility defaults
PAPER_SIM_STARTING_CASH_CENTS = max(100, _env_int("KALSHI_PAPER_SIM_STARTING_CASH_CENTS", 100_000))
PAPER_SIM_AGGRESSIVE_FILL_PROB = min(1.0, max(0.0, _env_float("KALSHI_PAPER_SIM_AGGRESSIVE_FILL_PROB", 0.92)))
PAPER_SIM_PASSIVE_BASE_FILL_PROB = min(1.0, max(0.0, _env_float("KALSHI_PAPER_SIM_PASSIVE_BASE_FILL_PROB", 0.35)))
PAPER_SIM_QUEUE_DECAY = max(0.0, _env_float("KALSHI_PAPER_SIM_QUEUE_DECAY", 0.12))
PAPER_SIM_QUEUE_AHEAD_FRACTION = max(0.0, _env_float("KALSHI_PAPER_SIM_QUEUE_AHEAD_FRACTION", 0.75))
PAPER_SIM_MIN_PARTIAL_FILL_FRACTION = min(1.0, max(0.01, _env_float("KALSHI_PAPER_SIM_MIN_PARTIAL_FILL_FRACTION", 0.2)))
PAPER_SIM_MAX_PARTIAL_FILL_FRACTION = min(1.0, max(PAPER_SIM_MIN_PARTIAL_FILL_FRACTION, _env_float("KALSHI_PAPER_SIM_MAX_PARTIAL_FILL_FRACTION", 0.7)))
PAPER_SIM_LATENCY_MS = max(0.0, _env_float("KALSHI_PAPER_SIM_LATENCY_MS", 120.0))
PAPER_SIM_PRICE_DRIFT_CENTS_PER_SEC = _env_float("KALSHI_PAPER_SIM_PRICE_DRIFT_CENTS_PER_SEC", 0.0)
PAPER_SIM_RANDOM_SEED = _env_int("KALSHI_PAPER_SIM_RANDOM_SEED", 20260508)


# Session export defaults
SESSION_EXPORT_ENABLED = _env_bool("KALSHI_SESSION_EXPORT_ENABLED", True)
SESSION_EXPORT_DIR = os.getenv("KALSHI_SESSION_EXPORT_DIR", "output/sessions")
SESSION_EXPORT_MAX_ROWS = max(200, _env_int("KALSHI_SESSION_EXPORT_MAX_ROWS", 5_000))
SESSION_EXPORT_CHART_DPI = max(90, _env_int("KALSHI_SESSION_EXPORT_CHART_DPI", 180))


# Monte Carlo simulation defaults
SIMULATION_OUTPUT_DIR = os.getenv("KALSHI_SIMULATION_OUTPUT_DIR", "output")
SIMULATION_MAX_PATHS = max(100, _env_int("KALSHI_SIMULATION_MAX_PATHS", 20_000))
SIMULATION_DEFAULT_N_PATHS = max(100, min(SIMULATION_MAX_PATHS, _env_int("KALSHI_SIMULATION_DEFAULT_N_PATHS", 5_000)))
SIMULATION_HORIZON_SECONDS = max(60, _env_int("KALSHI_SIMULATION_HORIZON_SECONDS", 900))
SIMULATION_DEFAULT_STEPS = max(60, _env_int("KALSHI_SIMULATION_DEFAULT_STEPS", 900))
SIMULATION_RANDOM_SEED = _env_int("KALSHI_SIMULATION_RANDOM_SEED", 20260508)
SIMULATION_PNG_WIDTH = max(800, _env_int("KALSHI_SIMULATION_PNG_WIDTH", 1800))
SIMULATION_PNG_HEIGHT = max(500, _env_int("KALSHI_SIMULATION_PNG_HEIGHT", 980))